- name: disable current version of sql
  ansible.builtin.command: dnf module disable mysql -y

- name: setup mysql5.7 repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql server
  ansible.builtin.yum:
    name: mysql-community-server
    state: present

- name: start and enable mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password # Below command is ansible refers to ssm parameter store for the manually store id
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ lookup
  ('aws_ssm', '/roboshop/{{env}}/mysql_root_pass', region='us-east-1' decrypt=True ) }}"